- name: Deploy Application
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Clone Git repository on control machine
      git:
        repo: https://github.com/NikhileshRedd/reactjs-demo.git
        dest: /home/ubuntu/repos/
        force: yes

    - name: Install Node.js and npm
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
        
    - name: Ensure git is installed
      package:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure git is installed
      yum:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'RedHat'

    - name: Clone the repository on servers
      git:
        repo: /home/ubuntu/repos/
        dest: /home/ubuntu/repos
      become: yes

    - name: Install Node.js and npm on servers
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm
      register: npm_install_result

    - name: Install dependencies 
      become: yes
      command: npm install
      args:

        chdir: /home/ubuntu/repos/

    - name: build React application
      become: yes
      command: npm run build
      args:

        chdir: /home/ubuntu/repos/
    - name: install apache on remote machine - Ubuntu
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "ubuntu"

    - name: install apache on remote machine - RedHat
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install Apache service on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family == 'Debian'

    - name: Install Apache service on RedHat
      service:
        name: httpd
        state: started
      when: ansible_os_family == 'RedHat'

    - name: Check if index.html exists
      stat:
        path: /home/ubuntu/repos/build/index.html
      register: index_html_check
      ignore_errors: yes

    - name: Copy artifact
      copy:
        src: /home/ubuntu/repos/build/index.html
        dest: /var/www/html/index.html
        remote_src: yes

