- name: Deploy Application
  hosts: webserver
  gather_facts: false
  become: yes

  tasks:
    - name: Clone Git repository on control machine
      git:
        repo: https://github.com/NikhileshRedd/reactjs-demo.git
        dest: /home/ubuntu/repos/

    - name: Install Node.js and npm
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm

- name: Setup Environment
  hosts: all
  become: yes
  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure git is installed
      yum:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'RedHat'

    - name: Clone the repository on servers
      git:
        repo: /home/ubuntu/repos/
        dest: /home/ubuntu/repos
      become: yes

    - name: Install Node.js and npm on servers
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm


- name: Deploy Application
  hosts: all
  become: yes

  tasks:
    - name: Check if index.html exists
      stat:
        path: /home/ubuntu/repos/build/index.html
      register: index_html_check
      ignore_errors: yes

    - name: Copy artifact
      copy:
        src: /home/ubuntu/repos/build/index.html
        dest: /var/www/html/
        remote_src: yes
      when: index_html_check.stat.exists | default(false)

    - name: Gather service facts
      service_facts:

    - name: Install Apache service on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_os_family == 'Debian'

    - name: Install Apache service on RedHat
      service:
        name: httpd
        state: started
      when: ansible_os_family == 'RedHat'

